title = "TOML Example"

[components]
[components.images.desert_icon]
mime = "image/jpeg"
base64 = "/9j/4AAQSkZJRgABAQEBLAEsAAD//gATQ3JlYXRlZCB3aXRoIEdJTVD/4gKwSUNDX1BST0ZJTEUAAQEAAAKgbGNtcwRAAABtbnRyUkdCIFhZWiAH5wAEAAkAFQAHABhhY3NwQVBQTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9tYAAQAAAADTLWxjbXMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1kZXNjAAABIAAAAEBjcHJ0AAABYAAAADZ3dHB0AAABmAAAABRjaGFkAAABrAAAACxyWFlaAAAB2AAAABRiWFlaAAAB7AAAABRnWFlaAAACAAAAABRyVFJDAAACFAAAACBnVFJDAAACFAAAACBiVFJDAAACFAAAACBjaHJtAAACNAAAACRkbW5kAAACWAAAACRkbWRkAAACfAAAACRtbHVjAAAAAAAAAAEAAAAMZW5VUwAAACQAAAAcAEcASQBNAFAAIABiAHUAaQBsAHQALQBpAG4AIABzAFIARwBCbWx1YwAAAAAAAAABAAAADGVuVVMAAAAaAAAAHABQAHUAYgBsAGkAYwAgAEQAbwBtAGEAaQBuAABYWVogAAAAAAAA9tYAAQAAAADTLXNmMzIAAAAAAAEMQgAABd7///MlAAAHkwAA/ZD///uh///9ogAAA9wAAMBuWFlaIAAAAAAAAG+gAAA49QAAA5BYWVogAAAAAAAAJJ8AAA+EAAC2xFhZWiAAAAAAAABilwAAt4cAABjZcGFyYQAAAAAAAwAAAAJmZgAA8qcAAA1ZAAAT0AAACltjaHJtAAAAAAADAAAAAKPXAABUfAAATM0AAJmaAAAmZwAAD1xtbHVjAAAAAAAAAAEAAAAMZW5VUwAAAAgAAAAcAEcASQBNAFBtbHVjAAAAAAAAAAEAAAAMZW5VUwAAAAgAAAAcAHMAUgBHAEL/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wgARCABIAEgDAREAAhEBAxEB/8QAGgAAAgMBAQAAAAAAAAAAAAAAAAECAwQFBv/EABkBAQEBAQEBAAAAAAAAAAAAAAABAgMEBf/aAAwDAQACEAMQAAAB9h6PPKVqhhDWNisnjYAgABAMIVCJWJEI5ltcuXUJcmpJNebKXLqVY3ZKSosxozSXB35h1fmevQVnC646XPc5WTKN55G8ZdLc3TnWmW7NnE1sjmXG+2+ESWEQWIzLc07z2+e5y2RaWQwP/8QAIxAAAgEEAgICAwAAAAAAAAAAAQIAAwQREhAUBRMhIjJAQf/aAAgBAQABBQLWazWazEwJgTAmOc/oG9Ea8Yw3dYQ3FZ1FZqbdmsxF64BvjO/UA+QEVnJpOpH5LTnXfL0ak1I4W8pGLdU1D3nx9wy3DCdowXLQ1mM/r+OdIVuKURg8CmBIEmORfrKN1TrFkpPOuk9DT1vNTy/j0aJ4tEOjTBgzATNptNhP/8QAIhEAAgIBAwQDAAAAAAAAAAAAAAEREiECAxATIDBBMUBh/9oACAEDAQE/AalSpUqVIIRX6rIwMy/ggqQQ0JNlNXsSyLb/AA6LHtMq1xZEokySSTxVFH6MoTnvsLUmQiO6p014P//EACMRAAICAgICAQUAAAAAAAAAAAABAhIRMRMhECBRAwQUIkD/2gAIAQIBAT8BsWLFixkyZLfx1KiSOkzZhI68YLxfSZKcY7OWL0xyWB/WXyfkxF9xBl09eONjjJ7FA6e0OKKFTGDkl8nKns/V6GseMmfTA4tFmi5Yz6KRymff/8QAKRAAAgEDAgQFBQAAAAAAAAAAAAERAiEiAzEQEiBBI2FxgZEyQFGhov/aAAgBAQAGPwL7vGmTGlI7fB9UehzJuS2ojKlMeH7JdKguoISbM00bWRagmyHEMyV/MZ3MZXsPl/qkmjU5fKC8M2R24bHg6nszxNNtfmks79dUzYiipNmdCMamizTNjZ8d6/klVVz69Wxsf//EACMQAAIBAwQCAwEAAAAAAAAAAAABESExkUFRYXEQgSChseH/2gAIAQEAAT8hC8ENyPmGESSSBJJJL+EEEE1a1Xxl103bJb2FRImm72E5gLuga7i5VetBVAzEqhsl+xVjlXgiY9uUTZPAzQi1apkWXXqDay+yZkTmJKBF6XL9q+xilJWlv2IbV8IjjK4QlQyyfjFFgm61F/BReYNsHnbA2HAldcVZwuMoDLxaj/Q/UQhKKgoFaKbEOCaUtQXUveBfUTqRIBru403xEeJah0FWNOU9AtSMCWIujExPqdBwcH//2gAMAwEAAgADAAAAEP5B1TYJAsgoYL/HVt1O11bXS+5SVGgvFpfPrdSlH/8A/8QAHREAAwEAAgMBAAAAAAAAAAAAAAERIRAxIEFRYf/aAAgBAwEBPxALgkgSEjKCoqKilNNNNIQhOIQhBNC30I0qJnRjWfQivZ+hwqTVqGeiTwNcQZ6CvYhHrTsNaKqicJHQ/kiPGJyxMWm1hLsXuQjoJCQkTmEYKG4z0TxaMSNN8//EAB4RAAMAAwACAwAAAAAAAAAAAAABERAhMUFRIHGB/9oACAECAQE/EA8FFFlicrGyMnxqKUpSlKUpflkLrGnCSCSSEW0TwPoSNyiZgf6Ia0EvqEqor1RrUrY83oXWqHuQaeDC7HsG1Sg1wgaiTgSlAuYe0M6GxhhvNtWG1YuJleUQyDWWIbNSIgpohM//xAAlEAEAAgEDBAICAwAAAAAAAAABABEhMUFRYXGBoZHB0fAQseH/2gAIAQEAAT8QFOpKbseZKYQo2itLI8zEcyu7GFZ0S3H8CrxG9klPEtxHoluIBAjqA5JTE6sQ5ZRywvgXei5hCheC/qMVFUwjjes+4JyeEAJ5ywyQVnHcXnP7mCN8ZRQ+EgsooK28QVKg0fYURJ2+BH2hfdbqHTWW5QprXldCAZVf0rCxCEhZRyvjpFAaJQWD3F0c1XJ2oYDPwwFkATJ09zA3FpXo4uDBomQUHWiHLQwuwfctOLdUOY9rtEC3w/1Hl3A2+gL6VC4qeoUfEsM3uP5lWTvhfmA0lXGmZFRRMGM9NII12tFi9z8RAFk2/wAH+RxLiZcDkTWUmHu4hE1Vm+v7USMZh9iaVBEgN+YPYjeopLYCohB7nUioi2xCzqOpLg9ca+8+4iYjxBco5KYVjd1LGokB2i9LI6FN9yPx3GBd7UGsJqWdLH3BLD4ZoXyEILx3mho94l1TnE7n2T//2Q=="

[components.images.tundra_icon]
mime = "image/png"
path = "/home/stephen/Documents/tundra.png"

[components.lights.darkness]
interface = "hue"

[components.sounds.lightning]

[components.playlists.desert]


[actions]
[actions.thunder_storm]
name = "Storm"
icon = "lightning"

[environments]
[environments.desert]
name = "Desert"
icon = "desert_icon"
actions = ["thunder_storm"]
on_entry = []
on_exit = []

[environments.desert2]
name = "Tundra"
icon = "tundra_icon"
actions = ["thunder_storm"]
on_entry = []
on_exit = []
